swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8081'
basePath: /
tags:
  - name: Auth
    description: Authentication Resources
  - name: Authentication
    description: Authentication Controller
paths:
  /authentGoogle:
    get:
      tags:
        - Auth
        - Authentication
      summary: GET A RANDOM KEY
      operationId: GET KEY
      produces:
        - application/json
      responses:
        '200':
          description: 'OK - String '
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/authentGoogle/{key}':
    get:
      tags:
        - Auth
        - Authentication
      summary: GET CODE OF KEY
      operationId: GET CODE
      produces:
        - application/json
      parameters:
        - name: key
          in: path
          description: Key
          required: true
          type: string
      responses:
        '200':
          description: 'OK - String '
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /authenticate/code:
    post:
      tags:
        - Auth
        - Authentication
      summary: LOG IN WITH CODE
      operationId: LOG IN WITH CODE
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: credential
          description: credential
          required: true
          schema:
            $ref: '#/definitions/Credentials'
      responses:
        '200':
          description: 'OK - AuthStatus '
          schema:
            $ref: '#/definitions/AuthStatus'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '503':
          description: Forbidden Access
          schema:
            type: string
      deprecated: false
  /authenticate/inscription:
    post:
      tags:
        - Auth
        - Authentication
      summary: REGISTER
      operationId: REGISTER
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: credential
          description: credential
          required: true
          schema:
            $ref: '#/definitions/Credentials'
      responses:
        '200':
          description: 'OK - String '
          schema:
            type: string
        '201':
          description: Created
        '204':
          description: User Mail already used
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /authenticate/login:
    post:
      tags:
        - Auth
        - Authentication
      summary: LOG IN
      operationId: LOG IN
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: credential
          description: credential
          required: true
          schema:
            $ref: '#/definitions/Credentials'
      responses:
        '200':
          description: 'OK - AuthStatus '
          schema:
            $ref: '#/definitions/AuthStatus'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '503':
          description: Forbidden Access
          schema:
            type: string
      deprecated: false
definitions:
  AuthStatus:
    type: object
    properties:
      stateAuthent:
        type: integer
        format: int32
      usrId:
        type: integer
        format: int64
      uuid:
        type: string
        format: uuid
    title: AuthStatus
    description: esipe.fr.model.AuthStatus
  Credentials:
    type: object
    properties:
      authenticated:
        type: boolean
      code:
        type: string
      login:
        type: string
      pwd:
        type: string
      usrId:
        type: integer
        format: int64
      uuid:
        type: string
        format: uuid
    title: Credentials
    description: esipe.fr.model.Credentials
