swagger: "2.0"
info:
  description: "API pour serveur de notifications"
  version: "1.0.0"
  title: "API notifs"
host: "http://172.31.254.54:8082/cloudito"
basePath: "/v1"
schemes:
- "https"
produces:
  - application/json
parameters:
  userId:
    name: userId
    in: path
    type: string
    description: identifiant de l'utilisateur
    required: true
  idNotif:
    name: idNotif
    in: path
    type: string
    description: id de la notification
    required: true
  pageSize:
    name: pageSize
    in: query
    type: number
    maximum: 50
    minimum: 0
    required: false
    description: le nombre de résultat dans la page, le nombre max est 50
  
paths:
  /notification:
    get:
      summary: liste toutes les notifications
      tags:
        - notification
      parameters:
        - name: order
          in: query
          type: string
          description: > 
            ordre de tri si il n'est pas précisé c'est le tri par la notification la plus récente
          required: false
        - $ref: '#/parameters/pageSize'
      responses:
        200:
          description: > 
            la liste des notifications, 
            si aucune notification ne correspond on retourne 200 
            avec un tableau vide
          schema:
            $ref: '#/definitions/notification'
        400:
          description: >
            si un des paramètres en entrée n'est pas valide, la category n'est pas dans l'enum
            le champ order n'est pas dans l'enum
          schema:
            $ref: '#/definitions/error'
    post:
      summary: ajout d'une notification 
      tags:
        - notification
      responses:
        200:
          description: la notification a été ajoutée
        403:
          description: vous n'êtes pas autorisé à ajouter une notification
          schema:
            $ref: '#/definitions/error'
    
  "/notification/{idNotif}":
    parameters:
    - $ref: '#/parameters/idNotif'
    get:
      summary: lecture d'une notification 
      tags:
        - notification
      responses:
        200:
          description: la notification a été récupérée
          schema:
            $ref: '#/definitions/notification'
        412:
          description: l id de la notification n est pas correct
          schema:
            $ref: '#/definitions/error'
      
    put:
      summary: mise à jour d une notification
      tags:
        - notification
      responses:
        200:
          description: la notification a été mise à jour
        412:
          description: l id de la notification n est pas correct
          schema:
            $ref: '#/definitions/error'  
    
    delete:
      summary: supprime la notification
      tags:
        - notification
      responses:
        200:
          description: la notification a été supprimée
        412:
          description: l id de la notification n est pas correct
          schema:
            $ref: '#/definitions/error'  
            
  "/user/notification/{userId}":
    parameters:
    - $ref: '#/parameters/userId'
    get:
      summary: lecture des notifications pour un utilisateur donné
      tags:
        - notification
      responses:
        200:
          description: la notification a été récupérée
          schema:
            $ref: '#/definitions/notification'
        412:
          description: l id de la notification n est pas correct
          schema:
            $ref: '#/definitions/error'
    
    delete:
      summary: supprime les notifications pour un utilisateur donné
      tags:
        - notification
      responses:
        200:
          description: la notification a été supprimée
        412:
          description: l id de la notification n est pas correct
          schema:
            $ref: '#/definitions/error'  
            
  
  
  
definitions:
  list:
    description: object générique pour des listes
    type: object
    properties:
      page: 
        type: number
        minimum: 0
        description: numéro de la page courante
      totalElements:
        description: nombre total d'éléments 
        type: number
        minimum: 0
      next: 
        type: string
        description: url de la prochaine page
  
  notification:
    type: object
    description: item ajouter à la commande ou au panier
    properties:
      id: 
        type: string
        description: reference de l'article
      texteNotif:
        type: string
        description: texte de la notification
      created:
        type: string
        format: date-time
        description: date de la création de la notif
      sent:
        type: string
        format: date-time
        description: date d'envoi de la notif
      updated:
        type: string
        format: date-time
        description: date d upload de la notif
      auteur:
        type: string
        description: auteur de la notification 
  error:
    type: object
    description: generic error
    properties:
      errorCode: 
        type: string
        description: code de l'erreur
      errorMessage:
        type: string
        description: message d'erreur
  