data :
  mysqldb :
    host : "172.31.254.54"
    port : 8006
    database : cloudito
    user : cloudito
    pwd : "1234"
grpc :
  client :
    host : "172.31.254.54"
    port : 3085
  server :
    port : 50051