data :
  mysqldb :
    host : "172.31.254.54"
    port : 8006
    database : cloudito
    user : cloudito
    pwd : "1234"
grpc :
  client :
    host : "localhost"
    port : 50051
  server :
    port : 50051
api:
  url: "http://172.31.254.54:3081"