# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recognize.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recognize.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0frecognize.proto\"\x15\n\x04\x46\x61\x63\x65\x12\r\n\x05value\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2)\n\tRecognize\x12\x1c\n\tRecognize\x12\x05.Face\x1a\x06.Empty\"\x00\x62\x06proto3'
)




_FACE = _descriptor.Descriptor(
  name='Face',
  full_name='Face',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Face.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=40,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=49,
)

DESCRIPTOR.message_types_by_name['Face'] = _FACE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Face = _reflection.GeneratedProtocolMessageType('Face', (_message.Message,), {
  'DESCRIPTOR' : _FACE,
  '__module__' : 'recognize_pb2'
  # @@protoc_insertion_point(class_scope:Face)
  })
_sym_db.RegisterMessage(Face)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'recognize_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)



_RECOGNIZE = _descriptor.ServiceDescriptor(
  name='Recognize',
  full_name='Recognize',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=51,
  serialized_end=92,
  methods=[
  _descriptor.MethodDescriptor(
    name='Recognize',
    full_name='Recognize.Recognize',
    index=0,
    containing_service=None,
    input_type=_FACE,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOGNIZE)

DESCRIPTOR.services_by_name['Recognize'] = _RECOGNIZE

# @@protoc_insertion_point(module_scope)
